### ISSUE TITLE
chore: 安装包证书无法验证

### ISSUE THREAD

**Issue by QingXia-Ela** [Baka632/MonsterSiren.Uwp#15]
如题，第一次安装可能遇到如下情况：

![图片](https://github.com/user-attachments/assets/59465756-ec26-4c8d-8588-8615bc4faf7b)

解决方法：https://blog.csdn.net/weixin_44786530/article/details/135319708

可以考虑在 Readme 加上解决方案

**Comment by Baka632** [comment]
我这个是自签名证书，所以会这样。
以后会考虑上架微软商店（
